---
title: The Same Faces
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'The Same Faces are an improvised comedy group, based in Leicester and
  Northampton.

'
baseurl: ''
url: https://www.thesamefaces.co.uk
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
